import { saveConversation } from "@/lib/actions/conversations";
import { createClient } from "@/lib/supabase/server";

vi.mock("@/lib/supabase/server", () => ({ createClient: vi.fn() }));

// ── Chainable Supabase stub ───────────────────────────────────────────────────

interface MockOptions {
  tier: "free" | "pro";
  savedCount: number;
  /** null → signed out. Defaults to a signed-in user. */
  user?: { id: string } | null;
  /** uuid resolved from the figure slug; null → slug lookup misses. */
  figureId?: string | null;
  /** When true, the messages insert returns an error to test the rollback path. */
  messagesInsertFails?: boolean;
}

interface RecordedInserts {
  conversations: unknown[];
  messages: unknown[];
  deletes: string[];
}

function makeBuilder(
  table: string,
  opts: Required<MockOptions>,
  inserts: RecordedInserts
) {
  const state = {
    op: "select" as "select" | "insert" | "delete",
    head: false,
    insertPayload: null as unknown,
    eqPairs: [] as Array<[string, unknown]>,
  };

  function resolve(): Promise<unknown> {
    if (table === "profiles") {
      return Promise.resolve({ data: { tier: opts.tier }, error: null });
    }
    if (table === "figures") {
      return Promise.resolve({
        data: opts.figureId ? { id: opts.figureId } : null,
        error: null,
      });
    }
    if (table === "conversations") {
      if (state.op === "insert") {
        return Promise.resolve({
          data: { id: "conv-1", ...(state.insertPayload as object) },
          error: null,
        });
      }
      if (state.op === "delete") {
        // Record the id being deleted (first eq value).
        const idPair = state.eqPairs.find(([col]) => col === "id");
        if (idPair) inserts.deletes.push(idPair[1] as string);
        return Promise.resolve({ data: null, error: null });
      }
      if (state.head) {
        return Promise.resolve({ count: opts.savedCount, error: null });
      }
      return Promise.resolve({ data: [], error: null });
    }
    // messages table
    if (table === "messages" && state.op === "insert") {
      if (opts.messagesInsertFails) {
        return Promise.resolve({
          data: null,
          error: { message: "messages insert failed" },
        });
      }
    }
    return Promise.resolve({ data: null, error: null });
  }

  const builder = {
    select(_columns?: string, options?: { count?: string; head?: boolean }) {
      if (options?.head) state.head = true;
      return builder;
    },
    insert(payload: unknown) {
      state.op = "insert";
      state.insertPayload = Array.isArray(payload) ? payload[0] : payload;
      inserts[table === "messages" ? "messages" : "conversations"].push(
        payload
      );
      return builder;
    },
    delete() {
      state.op = "delete";
      return builder;
    },
    eq(col: string, val: unknown) {
      state.eqPairs.push([col, val]);
      return builder;
    },
    order: () => builder,
    limit: () => builder,
    single: () => resolve(),
    maybeSingle: () => resolve(),
    then(
      onFulfilled?: (value: unknown) => unknown,
      onRejected?: (reason: unknown) => unknown
    ) {
      return resolve().then(onFulfilled, onRejected);
    },
  };
  return builder;
}

function mockSupabase(options: MockOptions): RecordedInserts {
  const opts: Required<MockOptions> = {
    user: { id: "user-1" },
    figureId: "fig-1",
    messagesInsertFails: false,
    ...options,
  };
  const inserts: RecordedInserts = { conversations: [], messages: [], deletes: [] };
  const client = {
    auth: {
      getUser: async () => ({ data: { user: opts.user }, error: null }),
    },
    from: (table: string) => makeBuilder(table, opts, inserts),
  };
  vi.mocked(createClient).mockResolvedValue(
    client as unknown as Awaited<ReturnType<typeof createClient>>
  );
  return inserts;
}

beforeEach(() => {
  vi.mocked(createClient).mockReset();
});

// ── Tests ─────────────────────────────────────────────────────────────────────

test("free user at 5 saved conversations is blocked with save-cap", async () => {
  mockSupabase({ tier: "free", savedCount: 5 });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [],
  });
  expect(res).toEqual({ ok: false, reason: "save-cap" });
});

test("pro user saves past 5", async () => {
  mockSupabase({ tier: "pro", savedCount: 12 });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [],
  });
  expect(res.ok).toBe(true);
});

test("title autogenerated from first question when missing", async () => {
  mockSupabase({ tier: "free", savedCount: 0 });
  const res = await saveConversation({
    figureSlug: "x",
    title: "",
    messages: [
      {
        role: "user",
        text: "Is America still fundamentally racist today and forever?",
      },
    ],
  });
  expect(res.title!.length).toBeLessThanOrEqual(60);
  expect(res.title).toMatch(/^Is America/);
});

test("unauthenticated user is rejected", async () => {
  mockSupabase({ tier: "free", savedCount: 0, user: null });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [],
  });
  expect(res).toEqual({ ok: false, reason: "unauthenticated" });
});

test("long first question is truncated to 60 chars", async () => {
  mockSupabase({ tier: "free", savedCount: 0 });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "",
    messages: [
      {
        role: "user",
        text: "What would you say about the rise of artificial intelligence and its effect on labor?",
      },
    ],
  });
  expect(res.ok).toBe(true);
  expect(res.title!.length).toBeLessThanOrEqual(60);
});

test("messages are inserted with the new conversation id", async () => {
  const inserts = mockSupabase({ tier: "free", savedCount: 1 });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [
      { role: "user", text: "q" },
      { role: "figure", text: "a", confidence: "strong" },
    ],
  });
  expect(res.ok).toBe(true);
  expect(inserts.conversations).toHaveLength(1);
  const rows = inserts.messages[0] as Array<Record<string, unknown>>;
  expect(rows).toHaveLength(2);
  expect(rows[0]).toMatchObject({
    conversation_id: "conv-1",
    role: "user",
    text: "q",
  });
  expect(rows[1]).toMatchObject({ role: "figure", confidence: "strong" });
});

test("figure slug lookup miss still saves with null figure_id", async () => {
  const inserts = mockSupabase({ tier: "free", savedCount: 0, figureId: null });
  const res = await saveConversation({
    figureSlug: "nobody",
    title: "t",
    messages: [],
  });
  expect(res.ok).toBe(true);
  const row = inserts.conversations[0] as Record<string, unknown>;
  expect(row).toMatchObject({ figure_id: null });
});

test("messages insert failure rolls back the conversation shell", async () => {
  const inserts = mockSupabase({
    tier: "free",
    savedCount: 0,
    messagesInsertFails: true,
  });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [{ role: "user", text: "test question" }],
  });
  expect(res).toEqual({ ok: false, reason: "error" });
  // The rollback delete must have targeted the just-created conversation shell.
  expect(inserts.deletes).toContain("conv-1");
});

test("null input is rejected with invalid-input", async () => {
  mockSupabase({ tier: "free", savedCount: 0 });
  const res = await saveConversation(null as never);
  expect(res).toEqual({ ok: false, reason: "invalid-input" });
});

test("null message in array is rejected with invalid-input", async () => {
  mockSupabase({ tier: "free", savedCount: 0 });
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: [null] as never,
  });
  expect(res).toEqual({ ok: false, reason: "invalid-input" });
});

test("201 messages is rejected with invalid-input", async () => {
  mockSupabase({ tier: "free", savedCount: 0 });
  const tooMany = Array.from({ length: 201 }, (_, i) => ({
    role: (i % 2 === 0 ? "user" : "figure") as "user" | "figure",
    text: "msg",
  }));
  const res = await saveConversation({
    figureSlug: "martin-luther-king",
    title: "t",
    messages: tooMany,
  });
  expect(res).toEqual({ ok: false, reason: "invalid-input" });
});
